# Generated by Django 2.2.4 on 2019-10-05 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('quantidade_funcionario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('texto', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('endereco', models.CharField(blank=True, max_length=11, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('Investigada', models.ManyToManyField(related_name='Investigadas', to='processo_eletronico.Pessoa')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Departamentos', to='processo_eletronico.Departamento')),
                ('interessada', models.ManyToManyField(related_name='Interessadas', to='processo_eletronico.Pessoa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pessoas', to='processo_eletronico.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='EnvioDeProcesso',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='processo_eletronico.Documento')),
                ('justificativa', models.CharField(max_length=50)),
                ('prazo_anterior', models.DateField()),
                ('novo_prazo', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('processo_eletronico.documento',),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='processo_eletronico.Pessoa')),
                ('matricula', models.IntegerField(null=True)),
                ('carga_horaria', models.IntegerField(null=True)),
                ('salario', models.CharField(max_length=150)),
            ],
            bases=('processo_eletronico.pessoa',),
        ),
        migrations.CreateModel(
            name='PedidoDePrazo',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='processo_eletronico.Documento')),
                ('justificativa', models.CharField(max_length=50)),
                ('prazo_anterior', models.DateField()),
                ('novo_prazo', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('processo_eletronico.documento',),
        ),
        migrations.CreateModel(
            name='PortariaDeInstauracao',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='processo_eletronico.Documento')),
                ('inicio_do_processo', models.DateTimeField(auto_now_add=True)),
                ('minuta', models.CharField(max_length=50)),
            ],
            bases=('processo_eletronico.documento',),
        ),
        migrations.CreateModel(
            name='Tramitacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimentacao', models.DateField()),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destino', to='processo_eletronico.Departamento')),
                ('origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origem', to='processo_eletronico.Departamento')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processo', to='processo_eletronico.Processo')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='processo',
            field=models.ManyToManyField(to='processo_eletronico.Processo'),
        ),
    ]
